# Auto-generated from /schema/chapter.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  chapter.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, constr


class Act(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    act_id: constr(pattern=r"^act_[a-z0-9_]{1,64}$") = Field(
        ...,
        description="Act id；pattern：'act_' 前缀 + 小写字母/数字/下划线。单 chapter 内唯一性留给 validator。",
    )
    display_name: constr(min_length=1)
    included_scenes: list[constr(min_length=1)] = Field(
        ...,
        description="本 act 包含的 scene_anchor 数组。可空（act 起步空场景）。每项必须解析回本体 location entity（location_type=scene）；闭合性留给 graph_validator。",
    )


class Chapter(BaseModel):
    """
    SCHEMA_v0.3.md §5 的 Chapter/Act 容器。验证对象 = /state/ontology/<world>.json 顶层 `chapters[]` 数组的元素。ADR-016 + U-CL-4：阶段 1/2 已生成内容到阶段 3 需回填层级——所以前移到阶段 2 起手期落地。`acts[]` 内嵌 act_id + included_scenes（scene_anchor 数组）；scene_anchor 闭合性留给 graph_validator（必须解析回 location entity 且 location_type=scene）。__留给 validator 的语义约束__：(1) `chapter_id` 全本体唯一；(2) `acts[].act_id` 在单 chapter 内唯一；(3) `acts[].included_scenes[]` 内每个 scene_anchor 在本体可解析。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["0.3.0"] = Field(
        "0.3.0",
        description="本 Chapter 对象的 schema 版本（SCHEMA_v0.3.md §1）。可省略，若填则必为 '0.3.0'。",
    )
    chapter_id: constr(pattern=r"^chap_[a-z0-9_]{1,64}$") = Field(
        ...,
        description="Chapter 全本体唯一 id。pattern：'chap_' 前缀 + 小写字母/数字/下划线。",
    )
    display_name: constr(min_length=1) = Field(
        ...,
        description="Chapter 人类可读名称；作者审阅 UI 显示 + prompt context 注入。",
    )
    acts: list[Act] = Field(
        ...,
        description="Act 数组。可空数组（chapter 起步空 acts，作者后续 L3 任务填充）。",
    )
