# Auto-generated from /schema/clock.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  clock.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Scope(Enum):
    """
    ADR-017 三档：world = 世界级（如战争进度）/ faction = 阵营级（铁誓声誉）/ environmental = 环境级（季节、瘟疫扩散）。
    """

    world = "world"
    faction = "faction"
    environmental = "environmental"


class Type(Enum):
    every_n_scenes = "every_n_scenes"
    on_long_rest = "on_long_rest"
    on_faction_action = "on_faction_action"
    on_player_choice = "on_player_choice"


class AdvanceRule(BaseModel):
    """
    ADR-017：clock 推进规则。`type` 仅四档 event_based 子类（every_n_scenes / on_long_rest / on_faction_action / on_player_choice）；**不存在 time_based 子类**——运行时无真时间，违反 ADR-002。`params` 自由 dict，由 effect 应用器（T-2.7）按 type 解释（如 every_n_scenes 需要 `n`；on_faction_action 需要 `faction_id`/`action_kind`）。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    params: dict[str, Any]


class EffectOp(Enum):
    """
    v1.0 §2.8：与 StateEffect.op 枚举完全一致；effect 应用器（T-2.7）用统一映射函数。
    """

    set = "set"
    inc = "inc"
    dec = "dec"
    add = "add"
    remove = "remove"


class PathItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class TickEffect(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    at_tick: conint(ge=1) = Field(
        ..., description="在第几格触发；validator 检查 1 <= at_tick <= ticks_total。"
    )
    effect_op: EffectOp = Field(
        ...,
        description="v1.0 §2.8：与 StateEffect.op 枚举完全一致；effect 应用器（T-2.7）用统一映射函数。",
    )
    path: constr(min_length=1) | list[PathItem] = Field(
        ...,
        description="状态总线键路径；表示法（点分字符串 vs 段数组）与 StateEffect.path 一致（D5 推迟项）。validator 校验落入 ADR-016 五个命名空间。",
    )
    value: Any = Field(
        ..., description="变更值；任意 JSON 类型（与 StateEffect.value 等价）。"
    )


class Clock(BaseModel):
    """
    SCHEMA_v0.3.md §4 的 Clock（PbtA Faction Clock 形态）。验证对象 = /state/ontology/<world>.json 顶层 `clocks[]` 数组的元素。ADR-017：三档 scope（world/faction/environmental）+ event_based advance_rule（不存在 time_based 子类，运行时无真时间——违反 ADR-002）。`ticks_total ≤ 20` 在 schema 层硬约（schema maximum）；同时活跃 clocks ≤ 10 由 T-2.7 sampling/validator 出 warning（schema 层不加，等实测倒推 ADR-017 v0.2 修订）。__留给 validator 的语义约束__：(1) `ticks_filled <= ticks_total`（schema 层无法跨字段表达）；(2) `tick_effects[].path` 落入 ADR-016 五个 state path 命名空间合法性；(3) `tick_effects[].at_tick <= ticks_total`；(4) `id` 全本体唯一性。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["0.3.0"] = Field(
        "0.3.0",
        description="本 Clock 对象的 schema 版本（SCHEMA_v0.3.md §1）。可省略，若填则必为 '0.3.0'。",
    )
    id: constr(pattern=r"^clk_[a-z0-9_]{1,64}$") = Field(
        ...,
        description="Clock 全本体唯一 id。pattern：'clk_' 前缀 + 小写字母/数字/下划线（后缀 1–64 字符）。",
    )
    name: constr(min_length=1) = Field(
        ..., description="Clock 人类可读名称；GraphContext 注入用 + 作者审阅 UI 显示。"
    )
    scope: Scope = Field(
        ...,
        description="ADR-017 三档：world = 世界级（如战争进度）/ faction = 阵营级（铁誓声誉）/ environmental = 环境级（季节、瘟疫扩散）。",
    )
    ticks_total: conint(ge=1, le=20) = Field(
        ...,
        description="PbtA 术语：clock 总格数。schema maximum 20（PZ §3.4 + ADR-017 边界）。最小 1。",
    )
    ticks_filled: conint(ge=0) = Field(
        ...,
        description="PbtA 术语：当前已填格数（**非 ticks_current**——避免与 game-loop counter 混淆）。schema 层不约 `ticks_filled <= ticks_total`，由 validator 兜底。",
    )
    advance_rule: AdvanceRule = Field(
        ...,
        description="ADR-017：clock 推进规则。`type` 仅四档 event_based 子类（every_n_scenes / on_long_rest / on_faction_action / on_player_choice）；**不存在 time_based 子类**——运行时无真时间，违反 ADR-002。`params` 自由 dict，由 effect 应用器（T-2.7）按 type 解释（如 every_n_scenes 需要 `n`；on_faction_action 需要 `faction_id`/`action_kind`）。",
    )
    tick_effects: list[TickEffect] | None = Field(
        None,
        description="🟡 ADR-017：tick 触发的状态效果（如 ticks_filled 达到某值时自动 set 一个 flag）。每项 `{at_tick, effect_op, path, value}`，effect_op 与 StateEffect.op 枚举一致（v1.0 §2.8）。可空数组（仅作进度展示，无 side effect）。",
    )
