# Auto-generated from /schema/dialogue_graph.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  dialogue_graph.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, constr

from . import node


class DialogueGraph(BaseModel):
    """
    SCHEMA_v0.md v0.1.1 §3.1 的 DialogueGraph 根对象。schema_version 锁定为 '0.1.1'；graph_id 全仓库唯一、D7 正则。nodes 采用 id→Node 的对象映射，node_id 唯一性由映射键天然保证。__留给 /validator 的跨对象约束__：graph_id 全仓库唯一性（跨文件/跨图）、entry_node_id ∈ nodes、任何 option.target_node_id ∈ nodes、speaker_ref ⊆ character_refs、可达性/死锁拓扑校验、本体锚点（scene_anchor / character_refs / location_ref / ontology_ref）在本体花名册中可解析——均留给 /validator。JSON Schema 能做的只有本文件/本对象范围内的结构与枚举。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["0.1.1"] = Field(
        ...,
        description="SCHEMA_v0.md §1：仅出现在根对象；本文件固定为 0.1.1。MAJOR 不同由 /engine /validator 按 §1.3 行为判断，不由本 JSON Schema 兼容。",
    )
    graph_id: constr(pattern=r"^[a-z0-9_-]+$", min_length=1, max_length=128) = Field(
        ...,
        description="D7：全仓库唯一（唯一性本身留给 /validator）。仅允许小写字母、数字、下划线、连字符；禁用空格、Unicode、'.'、':'、'/'。",
    )
    entry_node_id: constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=128) = (
        Field(
            ...,
            description="必须存在于 nodes map（闭合性留给 /validator）。D7 正则同 node_id。",
        )
    )
    nodes: dict[
        constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=128), node.Node
    ] = Field(
        ...,
        description="对象映射 node_id → Node。映射键天然保证 node_id 在图内唯一。至少 1 个节点。",
    )
    scene_anchor: constr(min_length=1) = Field(
        ...,
        description="本体场景/地点引用（闭合性留给 /validator + 本体 Schema 任务）。",
    )
    character_refs: list[constr(min_length=1)] = Field(
        ..., description="声明本图涉及的本体角色 ID（闭合性留给 /validator）。"
    )
    authoring: dict[str, Any] | None = Field(
        None,
        description="🟡 生成来源 / 审阅状态 / 主编签名；阶段 0 手写场景可空。内部结构后续任务固化。",
    )
    plugin_metadata: dict[str, Any] | None = Field(
        None, description="🟡 编剧理论插件的挂载点；核心层不解释内容。"
    )
    faction_clocks_touched: list[constr(min_length=1)] | None = Field(
        None, description="🟡 图可能推进/受影响的阵营时钟 ID 列表。阶段 0 可空。"
    )
