# Auto-generated from /schema/image_asset.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  image_asset.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class AssetKind(Enum):
    """
    资产种类（向后兼容名；与 asset_role 当前等价）。character_sheet=角色立绘；scene_background=场景背景。
    """

    character_sheet = "character_sheet"
    scene_background = "scene_background"


class TargetType(Enum):
    """
    Round 5 U-GPT-3 硬闸门：锚点类型。决定 character_ref / location_ref 镜像字段的语义有效性（在 image_validator 校验）。
    """

    character = "character"
    location = "location"
    scene = "scene"


class AssetRole(Enum):
    """
    Round 5 U-GPT-3 硬闸门：资产在叙事中扮演的角色。当前与 asset_kind 等价；枚举预留未来扩展（如 'item_icon' / 'ui_portrait'）的命名空间。
    """

    character_sheet = "character_sheet"
    scene_background = "scene_background"


class SourceMode(Enum):
    """
    ADR-014 双模生成策略。manual=作者从 ChatGPT 网页端手动生成后人工导入；api=OpenAI Image API 自动调用。
    """

    manual = "manual"
    api = "api"


class Format(Enum):
    """
    图像文件格式。
    """

    png = "png"
    webp = "webp"


class ImageAsset(BaseModel):
    """
    SCHEMA_v0.2.md §2 的 ImageAsset。视觉资产元数据：角色立绘（character_sheet）或场景背景（scene_background）。本对象 schema_version 起步 0.2.0；existing /schema/*.json 保持 0.1.1 不联动（STAGE_1.5_TASKS.md P0.5；沿用阶段 1 T-1.0 先例）。__留给 image_validator 的语义约束__：(1) target_type=character ⇒ character_ref==target_ref AND location_ref==null；(2) target_type∈{location,scene} ⇒ location_ref==target_ref AND character_ref==null；(3) asset_kind 与 asset_role 当前等价（重合是有意——asset_kind 是向后兼容名，asset_role 是 Round 5 U-GPT-3 硬闸门预留扩展位）；(4) target_ref / character_ref / location_ref 在本体花名册中可解析；(5) has_alpha 与 asset_role 一致性（character_sheet 应 true，scene_background 应 false）。一致性约束**不在 schema 层用 if/then/else / oneOf 表达**——阶段 1 baseline_001 教训：datamodel-code-generator 与 Gemini schema 子集对复合形态有已知坑（STAGE_1.5_TASKS.md P0.1）。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["0.2.0"] = Field(
        "0.2.0",
        description="本 ImageAsset 对象的 schema 版本（SCHEMA_v0.2.md §1）。项目首次新增 schema 文件起步 0.2.0；可省略，若填则必为 '0.2.0'。",
    )
    asset_id: constr(pattern=r"^img_[a-z0-9_]{1,64}$") = Field(
        ...,
        description="全仓库唯一资产 ID。pattern：'img_' 前缀 + 小写字母/数字/下划线（后缀 1–64 字符）。唯一性留给 image_validator。",
    )
    asset_kind: AssetKind = Field(
        ...,
        description="资产种类（向后兼容名；与 asset_role 当前等价）。character_sheet=角色立绘；scene_background=场景背景。",
    )
    target_ref: constr(min_length=1) = Field(
        ...,
        description="Round 5 U-GPT-3 硬闸门：通用挂载锚点 ID（如 'char_vellin' / 'scene_waystation_of_iron_oath'）。本体花名册闭合性留给 image_validator。",
    )
    target_type: TargetType = Field(
        ...,
        description="Round 5 U-GPT-3 硬闸门：锚点类型。决定 character_ref / location_ref 镜像字段的语义有效性（在 image_validator 校验）。",
    )
    asset_role: AssetRole = Field(
        ...,
        description="Round 5 U-GPT-3 硬闸门：资产在叙事中扮演的角色。当前与 asset_kind 等价；枚举预留未来扩展（如 'item_icon' / 'ui_portrait'）的命名空间。",
    )
    character_ref: str | None = Field(
        None,
        description="🟡 向后兼容镜像字段（与 target_ref + target_type=character 等价）。target_type=character 时，image_validator 要求 character_ref==target_ref；否则要求为 null。",
    )
    location_ref: str | None = Field(
        None,
        description="🟡 向后兼容镜像字段（与 target_ref + target_type∈{location,scene} 等价）。target_type∈{location,scene} 时，image_validator 要求 location_ref==target_ref；否则要求为 null。",
    )
    source_mode: SourceMode = Field(
        ...,
        description="ADR-014 双模生成策略。manual=作者从 ChatGPT 网页端手动生成后人工导入；api=OpenAI Image API 自动调用。",
    )
    format: Format = Field(..., description="图像文件格式。")
    width: conint(ge=256, le=4096) = Field(
        ...,
        description="宽度像素。最小 256（缩略图最低边界），最大 4096（API 上限 + 入库存储上限）。",
    )
    height: conint(ge=256, le=4096) = Field(..., description="高度像素。边界同 width。")
    file_size_bytes: conint(ge=1) | None = Field(
        None, description="🟡 文件字节数；可选预检字段（R8 机械预检器）。"
    )
    has_alpha: bool | None = Field(
        None,
        description="🟡 透明通道是否存在；与 asset_role 一致性留给 image_validator（character_sheet 应 true，scene_background 应 false）。",
    )
    file_path: constr(
        pattern=r"^content/visuals/[A-Za-z0-9_/-]+\.(png|webp)$", min_length=1
    ) = Field(
        ...,
        description="相对仓库根、仅允许入库后的 content/visuals/ 下 PNG/WEBP 路径（如 'content/visuals/vellin/img_vellin_neutral.png'）。pattern 阻断目录穿越（'..' 含点不在字符类内）/ 绝对路径 / 非 content/visuals/ 目录 — schema 源头收窄路径安全（review of T-1.5.2 #4.1）。",
    )
    prompt_hash: constr(pattern=r"^[a-f0-9]{64}$") | None = Field(
        None,
        description="🟡 生成时 prompt 文本的 sha256 hex；用于追溯。pattern 强制 64 位小写 hex（review of T-1.5.2 #4.2）。",
    )
    generation_metadata: dict[str, Any] | None = Field(
        None,
        description="🟡 自由 dict：含 prompt 文本 / 风格基准引用 / 时间戳 / API 调用元数据等；schema 不约束内部结构。",
    )
    style_reference_id: str | None = Field(
        None, description="🟡 指向 _reference/ 内的基准图标识；可选。"
    )
    reference_ids: list[constr(min_length=1)] | None = Field(
        [],
        description="Round 5 U-GPT-6 软闸门：本资产生成时引用的 _reference/ 基准图 ID 数组；用于 trace 风格依赖。开源剥离合规预防（C5 共识）。",
    )
    reference_license_note: str | None = Field(
        "",
        description="Round 5 U-GPT-6 软闸门：自由文本，作者填写每张引用基准图的来源 + 许可（如 'ref_001: own photograph CC0'）。开源剥离合规预防（C5 共识）。",
    )
    open_source_ok: bool | None = Field(
        False,
        description="Round 5 U-GPT-6 软闸门：本资产是否能进开源 release dataset。默认 false 安全侧。开源剥离合规预防（C5 共识）。",
    )
    commercial_ok: bool | None = Field(
        False,
        description="Round 5 U-GPT-6 软闸门：本资产是否能进商业版。默认 false 安全侧。开源剥离合规预防（C5 共识）。",
    )
    created_at: AwareDatetime = Field(
        ...,
        description="ISO 8601 / RFC 3339 date-time 字符串（format 由 image_validator 严格校验；schema 层仅约束类型）。",
    )
