# Auto-generated from /schema/node.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  dialogue_graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr

from . import option, state_condition, state_effect


class Type(Enum):
    """
    D1：dialogue = 有选项可继续；end = 终止节点（options 必为空数组）。旁白由 speaker_ref=null 表达，不作为独立类型。
    """

    dialogue = "dialogue"
    end = "end"


class DialogueItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    speaker_ref: constr(min_length=1) = Field(
        ...,
        description="本对白行说话人的本体角色引用；非 null。闭合性（∈ character_refs）留给 /validator。",
    )
    line: constr(min_length=1) = Field(
        ...,
        description="该说话人的一句对白裸正文；不含「」包裹体例（呈现由宿主/渲染层施加）。",
    )


class Source(Enum):
    human = "human"
    llm = "llm"


class SlotAssignments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    character_ref: constr(pattern=r"^char_[a-z0-9_]{1,64}$") = Field(
        ..., description="concrete character entity id；闭合性留给 graph_validator。"
    )
    assigned_at: constr(min_length=1) = Field(
        ..., description="ISO 8601 / RFC 3339 时间戳；T-2.6 写入。"
    )
    source_prompt_hash: str | None = Field(
        ...,
        description="生成此 slot 分配的 prompt 文本 sha256 hex（可 null，作者手填场景无 hash）。",
    )


class GenerationTrace(BaseModel):
    """
    🟡 D8：整体可省；若填则 source 必填，六键结构冻结（同 Option.generation_trace）。__v0.3 增量__（ADR-019 / SCHEMA_v0.3.md §6）：追加 optional `slot_assignments` 子字段，结构 `dict[<slot_id>, {character_ref, assigned_at, source_prompt_hash}]`，用于持久化 generator 中间产物的抽象槽 → concrete character 映射。**走 optional + additionalProperties: false 兼容路径——不 bump dialogue_graph / node schema_version**（v1.0 §2.4）；现有 v0.1.x trace（无 slot_assignments）继续合法。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source
    generated_at: str | None = None
    model_id: str | None = None
    prompt_hash: str | None = None
    reviewed_by: str | None = None
    reviewed_at: str | None = None
    slot_assignments: dict[str, SlotAssignments] | None = Field(
        None,
        description="🟡 v0.3 增量（ADR-019 / SCHEMA_v0.3.md §6）：节点级抽象槽 → concrete character 持久化映射。键 = slot_id（自由短文本，如 'the_betrayer' / 'the_witness'），值 = `{character_ref, assigned_at, source_prompt_hash}`。本字段 optional，整体可省；若填则每个 entry 必须三键齐全。槽位语义跨场景一致性留给 generator 中间产物层（阶段 2 不实现动态换角）。",
    )


class Node(BaseModel):
    """
    SCHEMA_v0.md v0.1.1 §3.2 的 Node。D1：type 枚举 dialogue/end；type=dialogue ⇒ options 非空数组，type=end ⇒ options 为空数组（用 allOf + if/then 表达）。D3：on_enter_effects 启用（🟡，可空）。D7：node_id 正则与长度。D8：generation_trace 可省，若填则 source 必填。__留给 /validator 的跨对象约束__：node_id 在 nodes map 内的唯一性由 map 键天然保证；entry_node_id ∈ nodes、speaker_ref 非 null 时 ∈ character_refs 的闭合性、option_id 在单 Node 内唯一性、图可达性/死锁等拓扑校验——均留给 /validator。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    node_id: constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=128) = Field(
        ...,
        description="D7：图内唯一（由 nodes map 键保证）。正则仅允许 [a-zA-Z0-9_-]。",
    )
    type: Type = Field(
        ...,
        description="D1：dialogue = 有选项可继续；end = 终止节点（options 必为空数组）。旁白由 speaker_ref=null 表达，不作为独立类型。",
    )
    narration: str = Field(..., description="玩家看到的场景/对白文本。")
    speaker_ref: str | None = Field(
        ...,
        description="本体角色引用；null 表示旁白（D1 决议配套）。闭合性留给 /validator。",
    )
    location_ref: str = Field(
        ...,
        description="本体地点引用；继承自图层 scene_anchor 或细化。闭合性留给 /validator。",
    )
    options: list[option.Option] = Field(
        ...,
        description="D1：dialogue 节点非空、end 节点为空数组（由本文件下方 allOf+if/then 强制）。",
    )
    dialogue: list[DialogueItem] | None = Field(
        None,
        description="⭐ ADR-040（B1 结构化对白）：narration 之外的结构化对白行；可选数组，可省。每项 {speaker_ref, line}：speaker_ref = 本对白行说话人的本体角色引用（非 null），line = 该说话人的一句对白裸正文（不含「」包裹体例，由宿主/渲染层施加）。narration 现语义 = 旁白（场景/动作白描，无说话人）；带说话人的台词进本数组。__本字段 optional + additionalProperties:false 兼容路径，不 bump schema_version__（沿用 generation_trace.slot_assignments / scene_metaparams 先例；不破 gold scene 与 const 守卫测试）。__留给 /validator__：(1) 每条 dialogue[].speaker_ref 必须 ∈ 父图 character_refs（闭合性，同 node.speaker_ref，由 consistency_check 校验）；(2) dialogue[].line 文本走反模式预检（anti_pattern_detector）。__语义不变量（ADR-040 决策三）__：节点携带非空 dialogue[] ⇒ narration 为纯旁白 ⇒ node.speaker_ref 应为 null；非空 node.speaker_ref 仅 legacy（pre-040）narration-only 节点保留。",
    )
    reachability_condition: state_condition.StateCondition | None = Field(
        None, description="🟡 节点可达性前置条件；阶段 0 手写场景可 null。"
    )
    on_enter_effects: list[state_effect.StateEffect] | None = Field(
        None, description="🟡 D3：进入节点时按数组顺序应用的状态效果。可空数组。"
    )
    background_seeds: list[constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1)] | None = (
        Field(
            None,
            description="⭐ T-3Y-1 / T-3Y 进展报告 §5.1：本节点承载的 seed_id 列表；与父图 scene_seeds[].planted_in_node_ids 双向引用。__留给 /validator__：(1) 每个 seed_id 必须在父图 scene_seeds 列表里存在；(2) 父图 scene_seeds 中 planted_in_node_ids 含本节点 ⇒ 本节点 background_seeds 必含该 seed_id（双向一致性）。本字段 optional，仅给 generator prompt 用，runtime engine 不读。",
        )
    )
    foreground_goal: (
        constr(pattern=r"^[a-z0-9_]+(\.stage_[1-9][0-9]*)?$", min_length=1) | None
    ) = Field(
        None,
        description="⭐ T-3Y-1 / T-3Y 进展报告 §5.1：本节点的前景目标，形如 '<reveal_id>.stage_<n>'（如 'r1_wright_double_life.stage_2'），声明本节点承载哪个 reveal 的哪个 stage。stage 后缀 optional（不分阶段的 reveal 可省略）。__留给 /validator__：(1) reveal_id 必须在父图 scene_reveals 列表内可解析；(2) stage 必须在 scene_reveals[].required_stages 范围内；(3) 父图 scene_reveals[].trigger_node_ids 含本节点 ⇒ 本节点 foreground_goal 必指向该 reveal。本字段 optional，仅给 generator prompt 用。__Codex review finding 4.2 收紧__：pattern 只允许小写蛇形 [a-z0-9_]，与 dialogue_graph.scene_reveals.reveal_id pattern 对齐（确保 D5 派生 knowledge.<reveal_id>.stage_<n> 合法）。",
    )
    plugin_metadata: dict[str, Any] | None = Field(
        None, description="🟡 编剧理论插件的挂载点。"
    )
    generation_trace: GenerationTrace | None = Field(
        None,
        description="🟡 D8：整体可省；若填则 source 必填，六键结构冻结（同 Option.generation_trace）。__v0.3 增量__（ADR-019 / SCHEMA_v0.3.md §6）：追加 optional `slot_assignments` 子字段，结构 `dict[<slot_id>, {character_ref, assigned_at, source_prompt_hash}]`，用于持久化 generator 中间产物的抽象槽 → concrete character 映射。**走 optional + additionalProperties: false 兼容路径——不 bump dialogue_graph / node schema_version**（v1.0 §2.4）；现有 v0.1.x trace（无 slot_assignments）继续合法。",
    )


Node.model_rebuild()
