# Auto-generated from /schema/node.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  dialogue_graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr

from . import option, state_condition, state_effect


class Type(Enum):
    """
    D1：dialogue = 有选项可继续；end = 终止节点（options 必为空数组）。旁白由 speaker_ref=null 表达，不作为独立类型。
    """

    dialogue = "dialogue"
    end = "end"


class Source(Enum):
    human = "human"
    llm = "llm"


class GenerationTrace(BaseModel):
    """
    🟡 D8：整体可省；若填则 source 必填，六键结构冻结（同 Option.generation_trace）。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source
    generated_at: str | None = None
    model_id: str | None = None
    prompt_hash: str | None = None
    reviewed_by: str | None = None
    reviewed_at: str | None = None


class Node(BaseModel):
    """
    SCHEMA_v0.md v0.1.1 §3.2 的 Node。D1：type 枚举 dialogue/end；type=dialogue ⇒ options 非空数组，type=end ⇒ options 为空数组（用 allOf + if/then 表达）。D3：on_enter_effects 启用（🟡，可空）。D7：node_id 正则与长度。D8：generation_trace 可省，若填则 source 必填。__留给 /validator 的跨对象约束__：node_id 在 nodes map 内的唯一性由 map 键天然保证；entry_node_id ∈ nodes、speaker_ref 非 null 时 ∈ character_refs 的闭合性、option_id 在单 Node 内唯一性、图可达性/死锁等拓扑校验——均留给 /validator。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    node_id: constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=128) = Field(
        ...,
        description="D7：图内唯一（由 nodes map 键保证）。正则仅允许 [a-zA-Z0-9_-]。",
    )
    type: Type = Field(
        ...,
        description="D1：dialogue = 有选项可继续；end = 终止节点（options 必为空数组）。旁白由 speaker_ref=null 表达，不作为独立类型。",
    )
    narration: str = Field(..., description="玩家看到的场景/对白文本。")
    speaker_ref: str | None = Field(
        ...,
        description="本体角色引用；null 表示旁白（D1 决议配套）。闭合性留给 /validator。",
    )
    location_ref: str = Field(
        ...,
        description="本体地点引用；继承自图层 scene_anchor 或细化。闭合性留给 /validator。",
    )
    options: list[option.Option] = Field(
        ...,
        description="D1：dialogue 节点非空、end 节点为空数组（由本文件下方 allOf+if/then 强制）。",
    )
    reachability_condition: state_condition.StateCondition | None = Field(
        None, description="🟡 节点可达性前置条件；阶段 0 手写场景可 null。"
    )
    on_enter_effects: list[state_effect.StateEffect] | None = Field(
        None, description="🟡 D3：进入节点时按数组顺序应用的状态效果。可空数组。"
    )
    plugin_metadata: dict[str, Any] | None = Field(
        None, description="🟡 编剧理论插件的挂载点。"
    )
    generation_trace: GenerationTrace | None = Field(
        None,
        description="🟡 D8：整体可省；若填则 source 必填，六键结构冻结（同 Option.generation_trace）。",
    )


Node.model_rebuild()
