# Auto-generated from /schema/option.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  dialogue_graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr

from . import state_condition, state_effect


class UnavailableBehavior(Enum):
    """
    D2：不满足 condition 时的呈现语义。
    """

    hide = "hide"
    disable = "disable"
    disable_with_hint = "disable_with_hint"


class Source(Enum):
    human = "human"
    llm = "llm"


class GenerationTrace(BaseModel):
    """
    🟡 D8：整体可省；若填则 source 必填，六键结构冻结。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source
    generated_at: str | None = None
    model_id: str | None = None
    prompt_hash: str | None = None
    reviewed_by: str | None = None
    reviewed_at: str | None = None


class Option(BaseModel):
    """
    SCHEMA_v0.md v0.1.1 §3.3 的 Option。D2：unavailable_behavior 枚举 hide/disable/disable_with_hint。D7：option_id 正则与长度。D8：generation_trace 整体可省，若填则 source 必填、六键固定。__留给 /validator 的跨对象约束__：option_id 在单 Node 内唯一性（JSON Schema 无法跨兄弟元素表达）、target_node_id 存在于同图 nodes map、effects 内 ontology_ref 的闭合性——均留给 /validator。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    option_id: constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=128) = (
        Field(
            ...,
            description="D7：节点内唯一（唯一性本身留给 /validator）。正则仅允许 [a-zA-Z0-9_-]。",
        )
    )
    text: str = Field(..., description="玩家可见文本。")
    target_node_id: constr(
        pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=128
    ) = Field(
        ...,
        description="D7 同 node_id。必须存在于同一图 nodes map（闭合性留给 /validator）。",
    )
    condition: state_condition.StateCondition | None = Field(
        ..., description="前置条件；null 表示无条件可选。"
    )
    effects: list[state_effect.StateEffect] = Field(
        ..., description="选中时触发的状态效果数组；可空。"
    )
    unavailable_behavior: UnavailableBehavior = Field(
        ..., description="D2：不满足 condition 时的呈现语义。"
    )
    generation_trace: GenerationTrace | None = Field(
        None, description="🟡 D8：整体可省；若填则 source 必填，六键结构冻结。"
    )
    plugin_metadata: dict[str, Any] | None = Field(
        None, description="🟡 编剧理论插件的挂载点；核心层不解释内容。"
    )


Option.model_rebuild()
