# Auto-generated from /schema/state_effect.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  dialogue_graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Op(Enum):
    """
    v0 候选枚举；/state 任务可能窄化/改动（D6 推迟）。
    """

    set = "set"
    inc = "inc"
    dec = "dec"
    add = "add"
    remove = "remove"


class PathItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class StateEffect(BaseModel):
    """
    SCHEMA_v0.md v0.1.1 §3.4 的 StateEffect。选项选中或进入节点时对状态总线的变更意图；op 白名单化（ADR-008）。__留给 /validator 的跨对象约束__：op 是否在 /state 白名单中最终命中、path 指向的键是否存在、ontology_ref 是否在本体花名册中可解析——这些要等 /state 任务完成后再按白名单校验。阶段 0 仅用候选起点枚举兜底。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Op = Field(
        ..., description="v0 候选枚举；/state 任务可能窄化/改动（D6 推迟）。"
    )
    path: constr(min_length=1) | list[PathItem] = Field(
        ...,
        description="状态总线键路径。表示法（点分字符串 vs 段数组）由 /state 任务最终确定（D5 推迟）。",
    )
    value: Any = Field(
        ..., description="变更值/参数；具体意义由 op 决定。任意 JSON 类型均可。"
    )
    ontology_ref: str | None = Field(
        None, description="🟡 当 op 涉及本体实体时填写；可为 null。"
    )
    faction_clock_op: dict[str, Any] | None = Field(
        None,
        description="🟡 阵营时钟专用子结构；阶段 0 不触发，内部结构推迟至 /state 任务。",
    )
