# Auto-generated from /schema/state_condition.schema.json by datamodel-code-generator. DO NOT EDIT MANUALLY. Re-run /generator/scripts/regenerate_models.sh
# generated by datamodel-codegen:
#   filename:  dialogue_graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Op(Enum):
    """
    v0 候选枚举；/state 任务可能窄化/改动（D6 推迟）。
    """

    eq = "eq"
    neq = "neq"
    gt = "gt"
    gte = "gte"
    lt = "lt"
    lte = "lte"
    has = "has"
    has_not = "has_not"


class PathItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class StateConditionLeaf(BaseModel):
    """
    叶条件形态：op + path + value 三键必填；不得与 all_of/any_of/not 混用（D4）。op 为 v0 候选起点，最终白名单推迟至 /state 任务（D6）。path 表示法点分字符串或段数组二选一，最终由 /state 任务固定（D5）。ontology_ref 为 🟡 可选。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    op: Op = Field(
        ..., description="v0 候选枚举；/state 任务可能窄化/改动（D6 推迟）。"
    )
    path: constr(min_length=1) | list[PathItem] = Field(
        ...,
        description="状态总线键路径。表示法（点分字符串 vs 段数组）由 /state 任务最终确定（D5 推迟）。",
    )
    value: Any = Field(..., description="与 path 指向值比较的值。任意 JSON 类型均可。")
    ontology_ref: str | None = Field(
        None, description="🟡 当条件涉及本体实体时填写；可为 null。"
    )


class StateConditionAllOf(BaseModel):
    """
    复合条件形态 all_of（D4）：all_of 必填；不得与 op/path/value/any_of/not 混用。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    all_of: list[StateCondition] = Field(..., min_length=1)
    ontology_ref: str | None = None


class StateConditionAnyOf(BaseModel):
    """
    复合条件形态 any_of（D4）：any_of 必填；不得与 op/path/value/all_of/not 混用。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    any_of: list[StateCondition] = Field(..., min_length=1)
    ontology_ref: str | None = None


class StateConditionNot(BaseModel):
    """
    复合条件形态 not（D4）：not 必填；不得与 op/path/value/all_of/any_of 混用。
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    not_: StateCondition = Field(..., alias="not")
    ontology_ref: str | None = None


class StateCondition(RootModel[StateConditionLeaf | StateConditionAllOf | StateConditionAnyOf | StateConditionNot]):
    root: StateConditionLeaf | StateConditionAllOf | StateConditionAnyOf | StateConditionNot = Field(
        ...,
        description="SCHEMA_v0.md v0.1.1 §3.5 的 StateCondition。D4：叶/复合两形态互斥——要么是 op+path+value 叶条件，要么恰好一个 all_of/any_of/not 复合键。嵌套经 $ref '#' 自引用实现。__留给 /validator 的跨对象约束__：图内 ID 唯一性（node_id 由 nodes map 键天然唯一、option_id 单 Node 内唯一）、引用闭合性（speaker_ref / target_node_id / entry_node_id 属于图内）、可达性（拓扑图论校验）——这些 JSON Schema 无法表达。",
        title="StateCondition",
    )


StateConditionAllOf.model_rebuild()
StateConditionAnyOf.model_rebuild()
StateConditionNot.model_rebuild()
